### ISSUE TITLE
LINUX freezes

### ISSUE THREAD

**Issue by nochadlee** [Jacudibu/PRUNner#11]
I use Linux,UBUNTU (20.04.1 LTS).
Unfortunately, PRUNner is constantly crashing.
Sometime after a few seconds, but there are times that I can use it for up to 10 minutes.
But, the end result is always the same. It freezes.
I really need the program PRUNner...

**Comment by Jacudibu** [comment]
Do you get any error message when running it via the command line?

**Comment by nochadlee** [comment]
No. No error message.
It just hangs.
I can't click on anything.
Nothing works.
I need to close the terminal window and restart it.
But then the same thing happens.
It works for a short time, then hangs again

**Comment by nochadlee** [comment]
Only the Linux version of Chrome (including Pros. Universe) is running in the background

**Comment by nochadlee** [comment]
But the problem is the same on several of my devices (notebook and PC as well)

**Comment by Jacudibu** [comment]
Mh, can't do much here since it works nice on my own machine and nobody else has had any problem like that so far. /:
Are you attempting to run it via the command line with `./PRUNner` or by some other means?

**Comment by nochadlee** [comment]
run it via the command line with ./PRUNner
...do i need to install some package for it?...

**Comment by Jacudibu** [comment]
Let's try this:
- Redownload the latest version (for linux that's [https://github.com/Jacudibu/PRUNner/releases/download/v0.3.5/PRUNner-0.3.5-linux-64.zip](https://github.com/Jacudibu/PRUNner/releases/download/v0.3.5/PRUNner-0.3.5-linux-64.zip)
- Unpack it
- Open a Terminal / Command Line window
- Navigate into the folder you just unpacked
- Enter `./PRUNner` to run it

The application shouldn't require any dependencies, but if you are missing anything for some reason there should be some sort of error message at this point. :)

**Comment by nochadlee** [comment]
...checking...

**Comment by nochadlee** [comment]
after 25 mins : hangs
![Képernyőkép erről: 2021-07-17 21-37-50](https://user-images.githubusercontent.com/64046118/126047801-8106fc38-cb98-4130-b03d-6e3a07f4d796.png)

**Comment by Jacudibu** [comment]
Can't reproduce this locally and the logs in this case don't help either, therefore can't fix it, sorry.
