### ISSUE TITLE
Missing Bonuses

### ISSUE THREAD

**Issue by nochadlee** [Jacudibu/PRUNner#12]
2 yes pounds bonus factor is missing.
The first is the base bonus given by the Base.
The second is the bonus from the Base level (Lv1 and above).
I think if that were also included in PRUNner, we would get much more accurate values of the daily production volume.

**Comment by Jacudibu** [comment]
I assume you mean the HQ bonuses as those are the only ones I'm aware of missing? 
I got those on my list and created an issue for them now (#13).

For me personally it's on a low priority to implement that right now, as I myself am usually capped in terms of base count and thus just don't need it.
