### ISSUE TITLE
Missing content on 4:3 screen

### ISSUE THREAD

**Issue by valuial** [Jacudibu/PRUNner#15]
Running PRUNner on my 4:3 screen with a 1280x1024 resolution, I am missing some window elements. This app appears to be optimized for wide screens only.

![image](https://user-images.githubusercontent.com/12469889/128729867-ec162ed3-a35e-4e96-8eff-de343a0d9800.png)

**Comment by valuial** [comment]
Oh right.
This is on Kubuntu 20.04

**Comment by Jacudibu** [comment]
Yeah, the app doesn't support small screen sizes right now, sorry about that!
Not sure when (or if) I'm going to fix that as I'm lacking the time right now, sorry.
