### ISSUE TITLE
feature request: Recipe Ratios

### ISSUE THREAD

**Issue by alxd3r** [Jacudibu/PRUNner#16]
Hi, I'm loving the tool but I'd like to suggest adding simpler a way to adjust the ratios of different recipes. For example, in my recipe queue, it may be optimal for me to produce 2 BBH and 1 BSE. I can add recipes for BBH and BSE and set them to 67% and 33% but it's not super accurate and I can make errors in my calculation for more complicated queues. It also means when adding extra recipes by default you're multiplying your production without adding in any more buildings. 

I'd love a way to adjust this automatically, something like an adjustable number next to each recipe, so I can set it to 2 BBH and 1 BSE or any other combination so I can find the optimal one without being scared I'll go too far off something the game can actually allow.

Thank you for this amazing tool,

alxder

**Comment by alxd3r** [comment]
In fact, thinking about it you pretty much already have a system for it, you can add multiples of the same recipes, if you just count the total sum it should be pretty easy to implement

**Comment by Jacudibu** [comment]
Hey! The latest version gets rid of the percentages and replaces them with an interface similar to how it would look in-game. Things should be way easier to set up now. :)
