### ISSUE TITLE
how is calculated the ROI for recipies?

### ISSUE THREAD

**Issue by jcornaz** [Jacudibu/PRUNner#20]
Hi, 

To me, ROI means "Returns over investment" and is (roughly) defined as: `profits / costs`. Therefore, the higher the profit and/or the lower the costs, the higher the ROI is.

But that is not what I observe in the tool. Quite the contrary, a see that a lower ROI seems to lead to higher profits.

Can you explain what is that ROI value?

**Comment by Jacudibu** [comment]
In our case the ROI value indicates how many days it would take to pay for the building, so smaller values indeed mean more money is being generated.

**Comment by jcornaz** [comment]
Ah... that is not ROI then, but a "Payback period".

May I suggest renaming this information for "Payback period" instead? And eventually, clarify the unit by adding a `d` after the value?
