### ISSUE TITLE
"No usable version of libssl was found" on Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by Tux0n0** [Jacudibu/PRUNner#28]
When trying to run PRUNner-0.5.0-linux-64 it outputs "No usable version of libssl was found" if run in console, unable to proceed any further.
Does it still use LibSSL1.0 (which is unavailable for modern Ubuntu)?

**Comment by Jacudibu** [comment]
Dunno, let's complain to Microsoft :upside_down_face: 
I will attempt updating the .Net Core runtime with the next update, maybe that fixes it, but no guarantees.

**Comment by Jacudibu** [comment]
Done. Can you try it again? :)

**Comment by Jacudibu** [comment]
Updated my own machine to a derivative of Ubuntu 22.04 and everything seems to work. Will close this for now.
