### ISSUE TITLE
NaN for Net Profit in latest commit (unreleased) 

### ISSUE THREAD

**Issue by louhy** [Jacudibu/PRUNner#36]
I like how in the last commit you allow production lines to go down to zero now (useful for quickly "toggling off" a production order to see the difference), and I was going to suggest this change. However I noticed that it does create a NaN problem for the monthly profit. Maybe a divide by zero going on somewhere. (LST order pictured) 

![image](https://user-images.githubusercontent.com/41243237/189765403-0fb8ba0a-f19d-4856-9ce8-63ad0dc71e44.png)

**Comment by louhy** [comment]
Slight amendment - I noticed that you only get NaN if the entire column has zero inputs (like the LST example). Definitely makes it less of an issue since you can always zero out the building count if you want to ignore that column entirely, but probably something worth addressing some day.

**Comment by Jacudibu** [comment]
Thanks, should be fixed now! :)
