### ISSUE TITLE
incorrect cycle time / output if using PIO/SET building without SETs

### ISSUE THREAD

**Issue by hollo6** [Jacudibu/PRUNner#6]
- I'm building a CHP without HB2, PWO only, PIO CoGC bonus, no experts
- the efficiency of the building should be : 0.23741007194244615
- which means FLX cycle time of: 50.545454545454522709090909090919 hours
- and a daily output of: 4.748201438848923
BUT:
![image](https://user-images.githubusercontent.com/365584/125086793-3dd12900-e0cc-11eb-8b11-06d2365cbc71.png)
![image](https://user-images.githubusercontent.com/365584/125086813-4164b000-e0cc-11eb-98b5-c800b426810f.png)

**Comment by hollo6** [comment]
I just did some more maths and it seems every cycle time in buildings with mixed workforce is calculated as if like all of them would have the same efficiency and them a little bit more off. See also: other recipes in CHP, HYF.

**Comment by Jacudibu** [comment]
Thanks! Should be fixed v0.3.4 :)
