### ISSUE TITLE
feature request: custom efficiency %

### ISSUE THREAD

**Issue by hollo6** [Jacudibu/PRUNner#8]
It would be nice to have a custom settable efficiency % boost option, for example, to be able to account for the unused base permits % increase.

**Comment by hollo6** [comment]
+ decrease for production line condition

**Comment by Jacudibu** [comment]
Good idea! That should be fairly easy to implement, just another multiplier for the efficiency calculation

**Comment by Jacudibu** [comment]
Just finished implementing it, will be added in the next update.
